### ISSUE TITLE
Symbols representing instance methods as keys not working

### ISSUE THREAD

**Issue by eprothro** [danpal/attr_encryptor#18]
``` ruby
class CreditApplication < ActiveRecord::Base
  attr_encrypted :ssn, :key => :encryption_key

  private

  def encryption_key
    case
    when Rails.env.production?
      raise 'ENV["ENCRYPTION_SECRET"] required to encrypt passwords in production.' unless ENV['ENCRYPTION_SECRET'].present?
      ENV['ENCRYPTION_SECRET']
    else
      # SecureRandom.base64(96)
      'non-prod:PlrWE7El5W2McZYWepI9BNdEK4wo2bTy87EFaI8NdI4gvnnSakVOK9Z/SnjmCndseARhG0FQMiPWD+XTpXHhmzaEwpVW0aZmmpbVXnDWcYTL9eEn2ZmqWxjrVcc2vJEG'
    end
  end
```

results in 

```
TypeError in Web::CreditApplicationsController#create

can't convert Symbol into String

Application Trace | Framework Trace | Full Trace
encryptor2 (1.0.0) lib/encryptor.rb:57:in `pbkdf2_hmac_sha1'
encryptor2 (1.0.0) lib/encryptor.rb:57:in `crypt'
encryptor2 (1.0.0) lib/encryptor.rb:31:in `encrypt'
attr_encryptor (1.0.2) lib/attr_encryptor.rb:217:in `encrypt'
attr_encryptor (1.0.2) lib/attr_encryptor.rb:293:in `encrypt'
attr_encryptor (1.0.2) lib/attr_encryptor.rb:147:in `block (2 levels) in attr_encrypted'
app/controllers/web/credit_applications_controller.rb:11:in `create'
.
.
.
```

Whereas using a proc works fine.

If I get time next week I'll fix and PR, but wanted to report the issue in case I couldn't get to it. Thanks!

**Comment by danpal** [comment]
Why are you using a symbol as a key? Of course keys have to be strings.

**Comment by eprothro** [comment]
Because the readme says that a symbol can be used to represent an instance method...

https://github.com/danpal/attr_encryptor#symbols-representing-instance-methods-as-keys

**Comment by danpal** [comment]
Yes, but a private methods are not instance methods.

**Comment by eprothro** [comment]
Ah, great point. I'm sure that was the issue; not sure how I overlooked that.
